### ISSUE TITLE
fiyat tablosu

### ISSUE THREAD

**Issue by coskuntekin** [bulutfon/apsiyon#1]
Rica etsem apsiyon.bulutfon.com sitesine aşağıdaki paketleri getirebilir misin? Fiyatları daire sayısına göre belirleyeceğiz. Toplam 4 adet olacak ve paket ismi olmayacak. İstersen bizim fiyatlar sayfası gibi yapabilirsin.

```
Daire                Aylık fiyat
```

 0  -  249                75 TL     + KDV
 250 - 499           150 TL    + KDV
 500 - 749           300 TL    + KDV
 750+                    600 TL    + KDV

**Comment by coskuntekin** [comment]
@onurozgurozkan fiyat tablosu sadece aylik mi olacak?

**Comment by onurozgurozkan** [comment]
@coskuntekin Yıllıkta olsun.
